export const SET_RESTAURANT = 'SET_RESTAURANT';
export const TOGGLE_REVIEW_MODAL = 'TOGGLE_REVIEW_MODAL';
export const SET_PLACE_TYPE = 'SET_PLACE_TYPE';
export const SET_SELF_LOCATION = 'SET_SELF_LOCATION';
